// <auto-generated />
namespace StudentManagerment2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class code5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(code5));
        
        string IMigrationMetadata.Id
        {
            get { return "202502171000057_code5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
